// Pre-optimized image variants generated by scripts/optimize-images.mjs.
const stem = (filename: string) => filename.replace(/\.jpg$/, '');

/** 1600px-wide WebP — page heroes and CSS backgrounds. */
export const heroSrc = (filename: string) => `/img/${stem(filename)}-1600.webp`;
/** 800px-wide WebP — product cards and content images. */
export const cardSrc = (filename: string) => `/img/${stem(filename)}-800.webp`;
/** 200×200 WebP — cart thumbnails and avatars. */
export const thumbSrc = (filename: string) => `/img/${stem(filename)}-thumb.webp`;

export const formatBaht = (n: number) => `฿${n.toLocaleString('en-US')}`;
