import type { Lang } from './i18n';

const dict = {
  th: {
    'nav.home': 'หน้าแรก',
    'nav.tours': 'ทัวร์ทั้งหมด',
    'nav.categories': 'หมวดหมู่ทัวร์',
    'nav.howToBook': 'วิธีจอง',
    'nav.contact': 'ติดต่อเรา',
    'nav.cart': 'ตะกร้าทัวร์',
    'common.from': 'เริ่มต้นที่',
    'common.perPerson': '/ ท่าน',
    'common.perVehicle': '/ ลำ',
    'common.perGroup': '/ กลุ่ม',
    'common.bookNow': 'จองเลย',
    'common.addToCart': 'ใส่ตะกร้า',
    'common.addedToCart': 'เพิ่มลงตะกร้าแล้ว ✓',
    'common.viewDetails': 'ดูรายละเอียด',
    'common.viewAllTours': 'ดูทัวร์ทั้งหมด',
    'common.allTours': 'ทัวร์ทั้งหมด',
    'common.adult': 'ผู้ใหญ่',
    'common.child': 'เด็ก',
    'common.program': 'โปรแกรม',
    'common.date': 'วันที่เดินทาง',
    'common.total': 'ราคารวม',
    'common.baht': 'บาท',
    'common.operatingDays': 'วันออกทัวร์',
    'tour.priceTable': 'ตารางราคา',
    'tour.itinerary': 'กำหนดการเดินทาง',
    'tour.includes': 'ราคานี้รวม',
    'tour.excludes': 'ราคานี้ไม่รวม',
    'tour.parkFees': 'ค่าธรรมเนียมอุทยาน',
    'tour.notes': 'หมายเหตุ',
    'tour.highlights': 'ไฮไลท์ของทริป',
    'tour.related': 'ทัวร์ใกล้เคียง',
    'booking.title': 'จองทัวร์นี้',
    'booking.selectProgram': 'เลือกโปรแกรม',
    'booking.adults': 'ผู้ใหญ่',
    'booking.children': 'เด็ก',
    'booking.dateRequired': 'กรุณาเลือกวันที่เดินทางก่อนจอง',
    'booking.note': 'ยังไม่ต้องชำระเงิน — ทีมงานยืนยันที่ว่างและราคาผ่าน LINE/WhatsApp ก่อนเสมอ',
    'cart.title': 'ตะกร้าทัวร์ของคุณ',
    'cart.empty': 'ตะกร้ายังว่างอยู่ — เลือกทัวร์ที่ถูกใจแล้วกลับมาจองได้เลย',
    'cart.browse': 'เลือกดูทัวร์',
    'cart.remove': 'ลบ',
    'cart.summary': 'สรุปการจอง',
    'cart.grandTotal': 'ราคารวมทั้งหมด',
    'cart.checkoutLine': 'ส่งคำจองผ่าน LINE',
    'cart.checkoutWa': 'ส่งคำจองผ่าน WhatsApp',
    'cart.checkoutMail': 'หรือส่งคำจองทางอีเมล',
    'cart.note': 'กดส่งคำจองแล้วระบบจะเปิดแชทพร้อมข้อความสรุปรายการให้อัตโนมัติ ทีมงานจะยืนยันที่ว่าง จุดรับ-ส่ง และวิธีชำระเงินในแชท ยังไม่มีการตัดเงินใดๆ',
    'cart.sent': 'ส่งคำจองแล้ว? ',
    'cart.clear': 'ล้างตะกร้า',
    'msg.heading': 'ขอจองทัวร์ — Phuket Love Paradise',
    'msg.program': 'โปรแกรม',
    'msg.date': 'วันที่',
    'msg.adults': 'ผู้ใหญ่',
    'msg.children': 'เด็ก',
    'msg.subtotal': 'รวม',
    'msg.total': 'ราคารวมทั้งหมด',
    'msg.name': 'ชื่อ',
    'msg.hotel': 'โรงแรม/ที่พัก',
    'msg.footer': '(ราคารอการยืนยันจากทีมงาน)',
    'msg.noDate': 'ยังไม่ระบุ',
  },
  en: {
    'nav.home': 'Home',
    'nav.tours': 'All Tours',
    'nav.categories': 'Categories',
    'nav.howToBook': 'How to Book',
    'nav.contact': 'Contact',
    'nav.cart': 'Tour cart',
    'common.from': 'From',
    'common.perPerson': '/ person',
    'common.perVehicle': '/ vehicle',
    'common.perGroup': '/ group',
    'common.bookNow': 'Book Now',
    'common.addToCart': 'Add to Cart',
    'common.addedToCart': 'Added to cart ✓',
    'common.viewDetails': 'View Details',
    'common.viewAllTours': 'View All Tours',
    'common.allTours': 'All Tours',
    'common.adult': 'Adult',
    'common.child': 'Child',
    'common.program': 'Program',
    'common.date': 'Travel date',
    'common.total': 'Total',
    'common.baht': 'THB',
    'common.operatingDays': 'Operating days',
    'tour.priceTable': 'Price list',
    'tour.itinerary': 'Itinerary',
    'tour.includes': 'Included',
    'tour.excludes': 'Not included',
    'tour.parkFees': 'National park fees',
    'tour.notes': 'Good to know',
    'tour.highlights': 'Trip highlights',
    'tour.related': 'You may also like',
    'booking.title': 'Book this tour',
    'booking.selectProgram': 'Choose a program',
    'booking.adults': 'Adults',
    'booking.children': 'Children',
    'booking.dateRequired': 'Please choose a travel date before booking.',
    'booking.note': 'No payment yet — our team always confirms availability and price via LINE/WhatsApp first.',
    'cart.title': 'Your Tour Cart',
    'cart.empty': 'Your cart is empty — pick a tour you love and come back to book.',
    'cart.browse': 'Browse tours',
    'cart.remove': 'Remove',
    'cart.summary': 'Booking summary',
    'cart.grandTotal': 'Grand total',
    'cart.checkoutLine': 'Send booking via LINE',
    'cart.checkoutWa': 'Send booking via WhatsApp',
    'cart.checkoutMail': 'or send your booking by email',
    'cart.note': 'Sending your booking opens a chat with a pre-filled summary. Our team confirms availability, pickup point and payment in chat — nothing is charged yet.',
    'cart.sent': 'Booking sent? ',
    'cart.clear': 'Clear cart',
    'msg.heading': 'Booking request — Phuket Love Paradise',
    'msg.program': 'Program',
    'msg.date': 'Date',
    'msg.adults': 'Adults',
    'msg.children': 'Children',
    'msg.subtotal': 'Subtotal',
    'msg.total': 'Total',
    'msg.name': 'Name',
    'msg.hotel': 'Hotel',
    'msg.footer': '(prices pending confirmation by our team)',
    'msg.noDate': 'not set',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.tours': 'Все туры',
    'nav.categories': 'Категории',
    'nav.howToBook': 'Как забронировать',
    'nav.contact': 'Контакты',
    'nav.cart': 'Корзина туров',
    'common.from': 'от',
    'common.perPerson': '/ чел.',
    'common.perVehicle': '/ ед.',
    'common.perGroup': '/ группа',
    'common.bookNow': 'Забронировать',
    'common.addToCart': 'В корзину',
    'common.addedToCart': 'Добавлено в корзину ✓',
    'common.viewDetails': 'Подробнее',
    'common.viewAllTours': 'Все туры',
    'common.allTours': 'Все туры',
    'common.adult': 'Взрослый',
    'common.child': 'Ребёнок',
    'common.program': 'Программа',
    'common.date': 'Дата поездки',
    'common.total': 'Итого',
    'common.baht': 'бат',
    'common.operatingDays': 'Дни туров',
    'tour.priceTable': 'Цены',
    'tour.itinerary': 'Программа тура',
    'tour.includes': 'Включено',
    'tour.excludes': 'Не включено',
    'tour.parkFees': 'Сборы нацпарка',
    'tour.notes': 'Полезно знать',
    'tour.highlights': 'Главное в туре',
    'tour.related': 'Похожие туры',
    'booking.title': 'Забронировать тур',
    'booking.selectProgram': 'Выберите программу',
    'booking.adults': 'Взрослые',
    'booking.children': 'Дети',
    'booking.dateRequired': 'Пожалуйста, выберите дату поездки перед бронированием.',
    'booking.note': 'Оплата не сейчас — наша команда сначала подтвердит наличие мест и цену в LINE/WhatsApp.',
    'cart.title': 'Ваша корзина туров',
    'cart.empty': 'Корзина пуста — выберите тур и возвращайтесь бронировать.',
    'cart.browse': 'Смотреть туры',
    'cart.remove': 'Удалить',
    'cart.summary': 'Сводка бронирования',
    'cart.grandTotal': 'Итого',
    'cart.checkoutLine': 'Отправить заявку в LINE',
    'cart.checkoutWa': 'Отправить заявку в WhatsApp',
    'cart.checkoutMail': 'или отправить заявку по эл. почте',
    'cart.note': 'После отправки откроется чат с готовой сводкой заказа. Команда подтвердит наличие, место трансфера и оплату в чате — деньги пока не списываются.',
    'cart.sent': 'Заявка отправлена? ',
    'cart.clear': 'Очистить корзину',
    'msg.heading': 'Заявка на бронирование — Phuket Love Paradise',
    'msg.program': 'Программа',
    'msg.date': 'Дата',
    'msg.adults': 'Взрослые',
    'msg.children': 'Дети',
    'msg.subtotal': 'Сумма',
    'msg.total': 'Итого',
    'msg.name': 'Имя',
    'msg.hotel': 'Отель',
    'msg.footer': '(цены будут подтверждены нашей командой)',
    'msg.noDate': 'не указана',
  },
} as const;

export type UiKey = keyof (typeof dict)['th'];

export const useT = (lang: Lang) => (key: UiKey) => dict[lang][key];

/** Subset of strings a client script needs, as a plain object for JSON embedding. */
export const uiSubset = (lang: Lang, keys: UiKey[]): Record<string, string> =>
  Object.fromEntries(keys.map((k) => [k, dict[lang][k]]));
